name: Validate Version Tag

on:
  pull_request:
    paths:
      - 'CHANGELOG.md'

jobs:
  check-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check if version is ready for release
        run: |
          echo "Checking CHANGELOG.md for unreleased changes..."
          
          if grep -q "## \[Unreleased\]" CHANGELOG.md; then
            echo "✓ Unreleased section exists"
            
            # Check if there's content in unreleased section
            UNRELEASED_CONTENT=$(awk '/## \[Unreleased\]/,/## \[/' CHANGELOG.md | sed '1d;$d' | grep -v "^$" || true)
            
            if [ -n "$UNRELEASED_CONTENT" ]; then
              echo "✓ Unreleased changes documented"
              echo ""
              echo "Unreleased changes:"
              echo "$UNRELEASED_CONTENT"
            else
              echo "⚠️ Warning: No unreleased changes documented"
            fi
          else
            echo "ℹ️ No [Unreleased] section found"
          fi

